### PR TITLE
Update dependencies to patch known vulnerabilities

### PR DESCRIPTION
**Pull request by dskrvk**

### CODE REVIEW

**Comment by dskrvk** [comment]
Hey @michaelwittig any feedback on this? My team is experiencing crashes in production with Node 8 - this and #3 fixes that.

**Comment by michaelwittig** [comment]
hi @dskrvk Can you test `node-heap-gc-cloudwatch@2.0.0` ?

**Comment by dskrvk** [comment]
Hey @michaelwittig will do! I already applied the patch from #3 in production, but now will update the package properly and let you know.

**Comment by dskrvk** [comment]
The new package version has been working fine for us on Node 8.

**Pull request merged**
